# Site settings

url: "http://alexlib.github.io/personal-jekyll-theme"
title: "{ Alex Liberzon }"
description: "Alex Liberzon"
keywords: "keywords"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

background-img: "/img/background.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "/img/career/onpu.jpg"
    date: "1986 - 1991"
    description: "Odessa Polytechnic University, Mechanical Engineering"
  - image: "/img/career/technion.png"
    date: "1991-2003"
    description: "B.Sc., M.Sc. Ph.D. (Cum Laude) Technion - Israel Institute of Technology"
  - image: "/img/career/eth.jpg"
    date: "2003-2006"
    description: "Postdoc at Institute of Hydromechanics, ETH Zurich"
  - image: "/img/career/tau.jpg"
    date: "2006 - Today"
    description: "Senior Lecturer (tenured 2010), Associate Professor (2011), School of Mechanical Engineering, Tel Aviv University"
  - image: "/img/career/lab1.jpg"
    date: "2006 - Today"
    description: "Head of Research Laboratory"
  - image: "/img/career/openpiv.png"
    date: "1998 - Today"
    description: "Open Source Particle Image Velocimetry, leading developer"
  - image: "/img/career/openptv.png"
    date: "2005 - Today"
    description: "Open Source Particle Tracking Velocimetry"

# First image of the Career timeline
career-img: "/img/career/lab.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/alexlib"
  - title: "linkedin"
    url: "https://il.linkedin.com/in/alexliberzon"
  - title: "youtube"
    url: "https://www.youtube.com/user/alex2lib"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
markdown: kramdown
